SELECT 
      [run_id]
      ,[year]
      ,[age]
      ,[sex]
      ,[ethnicity]
      ,[pop]
      ,[gq_mil]
      ,[gq_prison]
      ,[gq_college]
      ,[gq_other]
      ,[hh]
      ,[hh_size1]
      ,[hh_size2]
      ,[hh_size3]
      ,[hh_workers0]
      ,[hh_workers1]
      ,[hh_workers2]
      ,[hh_workers3]
      ,[hh_head_lf]
      ,[hh_children]
      ,[hh_seniors]
FROM [outputs].[population]
WHERE [run_id] = {run_id}
