version: "0.0.0-dev"
comments: "No Comments"
configurations:
  estimates_run_id: 237  # Estimates 2025 run
csv:
  fertility_rates: null
  migration_controls: null
  mortality_rates: null
interval:
  launch: 2022
  horizon: 2050
sql:
  load_to_database: False