version: "0.0.0-dev"
comments: "No Comments"
configurations:
  controls: "sandag_estimates.yml"
csv:
  migration_controls: null
  mortality_controls: null # Run mortality_forecasting.py first, then set to "output/mortality_forecast.csv"
  mortality_forecast_year: 2023
interval:
  launch: 2022
  horizon: 2050
sql:
  load_to_database: False