configurations:
  rates_map: "rates_map.JSON"
  controls: "sandag_estimates.JSON"
csv:
  dmdc_location_report: "data/DMDC Website Location Report.csv"
  sdmac_report: "data/SDMAC Report.csv"
  ss_life_table: "data/Social Security Actuarial Life Table.csv"
interval:
  launch: 2020
  horizon: 2050
output:
  overwrite: true
  files:
    components: "output/components.csv"
    population: "output/population.csv"
    rates: "output/rates.csv"
sql:
  datasets:
    acs5yr_pums_ca_mil: "sql/acs5yr_pums_ca_mil.sql"
    acs5yr_pums_migrants: "sql/acs5yr_pums_migrants.sql"
    acs5yr_pums_persons: "sql/acs5yr_pums_persons.sql"
    census_redistricting: "sql/census_redistricting.sql"
    dof_estimates: "sql/dof_estimates.sql"
    dof_projections: "sql/dof_projections.sql"
