version: "0.0.0-dev"
comments: "No Comments"
configurations:
  controls: "sandag_estimates.yml"
csv:
  migration_controls: null
  mortality_rates: null
interval:
  launch: 2022
  horizon: 2050
sql:
  load_to_database: False